//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Final.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


 using AntlrCSharp;
 
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class FinalLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, CON=4, EQU=5, IF=6, ELIF=7, ELSE=8, WHILE=9, FOR=10, 
		IN=11, BREAK=12, CONTINUE=13, RETURN=14, DEF=15, END=16, NEWLINE=17, WS=18, 
		EQUALS=19, STAR=20, ARITHMETIC=21, INTEGER=22, BOOLEAN=23, FLOATS=24, 
		STRING=25, COMMENT=26, ID=27, NL=28;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "LOWERCASE", "UPPERCASE", "CON", "EQU", "IF", 
		"ELIF", "ELSE", "WHILE", "FOR", "IN", "BREAK", "CONTINUE", "RETURN", "DEF", 
		"END", "NEWLINE", "WS", "EQUALS", "STAR", "ARITHMETIC", "INTEGER", "BOOLEAN", 
		"FLOATS", "STRING", "COMMENT", "ID", "NL"
	};


	 private DenterHelper denter;
	  
	 public override IToken NextToken()
	 {
	     if (denter == null)
	     {
	         denter = DenterHelper.Builder()
	             .Nl(NL)
	             .Indent(FinalParser.INDENT)
	             .Dedent(FinalParser.DEDENT)
	             .PullToken(base.NextToken);
	     }

	     return denter.NextToken();
	 }
	 

	public FinalLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public FinalLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "','", null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "'*'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "CON", "EQU", "IF", "ELIF", "ELSE", "WHILE", "FOR", 
		"IN", "BREAK", "CONTINUE", "RETURN", "DEF", "END", "NEWLINE", "WS", "EQUALS", 
		"STAR", "ARITHMETIC", "INTEGER", "BOOLEAN", "FLOATS", "STRING", "COMMENT", 
		"ID", "NL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Final.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static FinalLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1E', '\xFE', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x5', '\a', 'R', '\n', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '^', '\n', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x6', '\x14', '\x97', '\n', '\x14', '\r', 
		'\x14', '\xE', '\x14', '\x98', '\x3', '\x15', '\x6', '\x15', '\x9C', '\n', 
		'\x15', '\r', '\x15', '\xE', '\x15', '\x9D', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x5', '\x18', '\xA9', '\n', '\x18', '\x3', 
		'\x19', '\x5', '\x19', '\xAC', '\n', '\x19', '\x3', '\x19', '\x6', '\x19', 
		'\xAF', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\xB0', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x5', '\x1A', '\xC5', '\n', '\x1A', '\x3', 
		'\x1B', '\x5', '\x1B', '\xC8', '\n', '\x1B', '\x3', '\x1B', '\a', '\x1B', 
		'\xCB', '\n', '\x1B', '\f', '\x1B', '\xE', '\x1B', '\xCE', '\v', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x6', '\x1B', '\xD2', '\n', '\x1B', '\r', 
		'\x1B', '\xE', '\x1B', '\xD3', '\x3', '\x1C', '\x3', '\x1C', '\a', '\x1C', 
		'\xD8', '\n', '\x1C', '\f', '\x1C', '\xE', '\x1C', '\xDB', '\v', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\a', '\x1D', 
		'\xE1', '\n', '\x1D', '\f', '\x1D', '\xE', '\x1D', '\xE4', '\v', '\x1D', 
		'\x3', '\x1E', '\x3', '\x1E', '\x6', '\x1E', '\xE8', '\n', '\x1E', '\r', 
		'\x1E', '\xE', '\x1E', '\xE9', '\x3', '\x1F', '\a', '\x1F', '\xED', '\n', 
		'\x1F', '\f', '\x1F', '\xE', '\x1F', '\xF0', '\v', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\a', '\x1F', '\xF4', '\n', '\x1F', '\f', '\x1F', '\xE', 
		'\x1F', '\xF7', '\v', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x5', '\x1F', '\xFD', '\n', '\x1F', '\x3', '\xD9', '\x2', 
		' ', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x2', '\v', '\x2', 
		'\r', '\x6', '\xF', '\a', '\x11', '\b', '\x13', '\t', '\x15', '\n', '\x17', 
		'\v', '\x19', '\f', '\x1B', '\r', '\x1D', '\xE', '\x1F', '\xF', '!', '\x10', 
		'#', '\x11', '%', '\x12', '\'', '\x13', ')', '\x14', '+', '\x15', '-', 
		'\x16', '/', '\x17', '\x31', '\x18', '\x33', '\x19', '\x35', '\x1A', '\x37', 
		'\x1B', '\x39', '\x1C', ';', '\x1D', '=', '\x1E', '\x3', '\x2', '\t', 
		'\x3', '\x2', '\x63', '|', '\x3', '\x2', '\x43', '\\', '\x4', '\x2', '\f', 
		'\f', '\xF', '\xF', '\x3', '\x2', '\"', '\"', '\x4', '\x2', '-', '-', 
		'/', '/', '\x4', '\x2', '\'', '\'', '\x31', '\x31', '\x3', '\x2', '\x32', 
		';', '\x2', '\x115', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '?', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\a', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\t', '\x45', '\x3', '\x2', '\x2', '\x2', '\v', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\r', 'Q', '\x3', '\x2', '\x2', '\x2', '\xF', ']', '\x3', 
		'\x2', '\x2', '\x2', '\x11', '_', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '\x15', 'g', '\x3', '\x2', '\x2', 
		'\x2', '\x17', 'l', '\x3', '\x2', '\x2', '\x2', '\x19', 'r', '\x3', '\x2', 
		'\x2', '\x2', '\x1B', 'v', '\x3', '\x2', '\x2', '\x2', '\x1D', 'y', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\x7F', '\x3', '\x2', '\x2', '\x2', '!', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '#', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '%', '\x93', '\x3', '\x2', '\x2', '\x2', '\'', '\x96', '\x3', '\x2', 
		'\x2', '\x2', ')', '\x9B', '\x3', '\x2', '\x2', '\x2', '+', '\xA1', '\x3', 
		'\x2', '\x2', '\x2', '-', '\xA3', '\x3', '\x2', '\x2', '\x2', '/', '\xA8', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\xAB', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\xC4', '\x3', '\x2', '\x2', '\x2', '\x35', '\xC7', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\xD5', '\x3', '\x2', '\x2', '\x2', '\x39', '\xDE', 
		'\x3', '\x2', '\x2', '\x2', ';', '\xE7', '\x3', '\x2', '\x2', '\x2', '=', 
		'\xFC', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '*', '\x2', '\x2', 
		'@', '\x4', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '+', '\x2', 
		'\x2', '\x42', '\x6', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', 
		'.', '\x2', '\x2', '\x44', '\b', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', 
		'\t', '\x2', '\x2', '\x2', '\x46', '\n', '\x3', '\x2', '\x2', '\x2', 'G', 
		'H', '\t', '\x3', '\x2', '\x2', 'H', '\f', '\x3', '\x2', '\x2', '\x2', 
		'I', 'J', '\a', '\x63', '\x2', '\x2', 'J', 'K', '\a', 'p', '\x2', '\x2', 
		'K', 'R', '\a', '\x66', '\x2', '\x2', 'L', 'M', '\a', 'q', '\x2', '\x2', 
		'M', 'R', '\a', 't', '\x2', '\x2', 'N', 'O', '\a', 'p', '\x2', '\x2', 
		'O', 'P', '\a', 'q', '\x2', '\x2', 'P', 'R', '\a', 'v', '\x2', '\x2', 
		'Q', 'I', '\x3', '\x2', '\x2', '\x2', 'Q', 'L', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'N', '\x3', '\x2', '\x2', '\x2', 'R', '\xE', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\a', '?', '\x2', '\x2', 'T', '^', '\a', '?', '\x2', 
		'\x2', 'U', 'V', '\a', '#', '\x2', '\x2', 'V', '^', '\a', '?', '\x2', 
		'\x2', 'W', '^', '\a', '>', '\x2', '\x2', 'X', 'Y', '\a', '>', '\x2', 
		'\x2', 'Y', '^', '\a', '?', '\x2', '\x2', 'Z', '^', '\a', '@', '\x2', 
		'\x2', '[', '\\', '\a', '@', '\x2', '\x2', '\\', '^', '\a', '?', '\x2', 
		'\x2', ']', 'S', '\x3', '\x2', '\x2', '\x2', ']', 'U', '\x3', '\x2', '\x2', 
		'\x2', ']', 'W', '\x3', '\x2', '\x2', '\x2', ']', 'X', '\x3', '\x2', '\x2', 
		'\x2', ']', 'Z', '\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', 
		'\x2', '^', '\x10', '\x3', '\x2', '\x2', '\x2', '_', '`', '\a', 'k', '\x2', 
		'\x2', '`', '\x61', '\a', 'h', '\x2', '\x2', '\x61', '\x12', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '\x63', '\a', 'g', '\x2', '\x2', '\x63', '\x64', 
		'\a', 'n', '\x2', '\x2', '\x64', '\x65', '\a', 'k', '\x2', '\x2', '\x65', 
		'\x66', '\a', 'h', '\x2', '\x2', '\x66', '\x14', '\x3', '\x2', '\x2', 
		'\x2', 'g', 'h', '\a', 'g', '\x2', '\x2', 'h', 'i', '\a', 'n', '\x2', 
		'\x2', 'i', 'j', '\a', 'u', '\x2', '\x2', 'j', 'k', '\a', 'g', '\x2', 
		'\x2', 'k', '\x16', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', 'y', '\x2', 
		'\x2', 'm', 'n', '\a', 'j', '\x2', '\x2', 'n', 'o', '\a', 'k', '\x2', 
		'\x2', 'o', 'p', '\a', 'n', '\x2', '\x2', 'p', 'q', '\a', 'g', '\x2', 
		'\x2', 'q', '\x18', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', 'h', '\x2', 
		'\x2', 's', 't', '\a', 'q', '\x2', '\x2', 't', 'u', '\a', 't', '\x2', 
		'\x2', 'u', '\x1A', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\a', 'k', '\x2', 
		'\x2', 'w', 'x', '\a', 'p', '\x2', '\x2', 'x', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'z', '\a', '\x64', '\x2', '\x2', 'z', '{', '\a', 't', '\x2', 
		'\x2', '{', '|', '\a', 'g', '\x2', '\x2', '|', '}', '\a', '\x63', '\x2', 
		'\x2', '}', '~', '\a', 'm', '\x2', '\x2', '~', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x80', '\a', '\x65', '\x2', '\x2', '\x80', '\x81', '\a', 
		'q', '\x2', '\x2', '\x81', '\x82', '\a', 'p', '\x2', '\x2', '\x82', '\x83', 
		'\a', 'v', '\x2', '\x2', '\x83', '\x84', '\a', 'k', '\x2', '\x2', '\x84', 
		'\x85', '\a', 'p', '\x2', '\x2', '\x85', '\x86', '\a', 'w', '\x2', '\x2', 
		'\x86', '\x87', '\a', 'g', '\x2', '\x2', '\x87', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\x88', '\x89', '\a', 't', '\x2', '\x2', '\x89', '\x8A', '\a', 
		'g', '\x2', '\x2', '\x8A', '\x8B', '\a', 'v', '\x2', '\x2', '\x8B', '\x8C', 
		'\a', 'w', '\x2', '\x2', '\x8C', '\x8D', '\a', 't', '\x2', '\x2', '\x8D', 
		'\x8E', '\a', 'p', '\x2', '\x2', '\x8E', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x8F', '\x90', '\a', '\x66', '\x2', '\x2', '\x90', '\x91', '\a', 'g', 
		'\x2', '\x2', '\x91', '\x92', '\a', 'h', '\x2', '\x2', '\x92', '$', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x94', '\a', '<', '\x2', '\x2', '\x94', 
		'&', '\x3', '\x2', '\x2', '\x2', '\x95', '\x97', '\t', '\x4', '\x2', '\x2', 
		'\x96', '\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', 
		'\x2', '\x2', '\x98', '\x96', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '(', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9C', '\t', '\x5', '\x2', '\x2', '\x9B', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\b', '\x15', '\x2', 
		'\x2', '\xA0', '*', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\a', 
		'?', '\x2', '\x2', '\xA2', ',', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', 
		'\a', ',', '\x2', '\x2', '\xA4', '.', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA9', '\t', '\x6', '\x2', '\x2', '\xA6', '\xA9', '\x5', '-', '\x17', 
		'\x2', '\xA7', '\xA9', '\t', '\a', '\x2', '\x2', '\xA8', '\xA5', '\x3', 
		'\x2', '\x2', '\x2', '\xA8', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xA9', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xAA', '\xAC', '\a', '/', '\x2', '\x2', '\xAB', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAF', '\t', '\b', '\x2', 
		'\x2', '\xAE', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB0', '\x3', 
		'\x2', '\x2', '\x2', '\xB0', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xB1', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB3', '\a', 'V', '\x2', '\x2', '\xB3', '\xB4', '\a', 
		't', '\x2', '\x2', '\xB4', '\xB5', '\a', 'w', '\x2', '\x2', '\xB5', '\xC5', 
		'\a', 'g', '\x2', '\x2', '\xB6', '\xB7', '\a', 'v', '\x2', '\x2', '\xB7', 
		'\xB8', '\a', 't', '\x2', '\x2', '\xB8', '\xB9', '\a', 'w', '\x2', '\x2', 
		'\xB9', '\xC5', '\a', 'g', '\x2', '\x2', '\xBA', '\xBB', '\a', 'H', '\x2', 
		'\x2', '\xBB', '\xBC', '\a', '\x63', '\x2', '\x2', '\xBC', '\xBD', '\a', 
		'n', '\x2', '\x2', '\xBD', '\xBE', '\a', 'u', '\x2', '\x2', '\xBE', '\xC5', 
		'\a', 'g', '\x2', '\x2', '\xBF', '\xC0', '\a', 'h', '\x2', '\x2', '\xC0', 
		'\xC1', '\a', '\x63', '\x2', '\x2', '\xC1', '\xC2', '\a', 'n', '\x2', 
		'\x2', '\xC2', '\xC3', '\a', 'u', '\x2', '\x2', '\xC3', '\xC5', '\a', 
		'g', '\x2', '\x2', '\xC4', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xB6', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xBA', '\x3', '\x2', '\x2', 
		'\x2', '\xC4', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC5', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xC6', '\xC8', '\a', '/', '\x2', '\x2', '\xC7', 
		'\xC6', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\xC8', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCB', '\t', 
		'\b', '\x2', '\x2', '\xCA', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xCB', 
		'\xCE', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCC', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCF', '\x3', 
		'\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCF', 
		'\xD1', '\a', '\x30', '\x2', '\x2', '\xD0', '\xD2', '\t', '\b', '\x2', 
		'\x2', '\xD1', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD3', '\x3', 
		'\x2', '\x2', '\x2', '\xD3', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD3', 
		'\xD4', '\x3', '\x2', '\x2', '\x2', '\xD4', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xD5', '\xD9', '\a', '$', '\x2', '\x2', '\xD6', '\xD8', '\v', 
		'\x2', '\x2', '\x2', '\xD7', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD8', 
		'\xDB', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\x3', '\x2', '\x2', 
		'\x2', '\xD9', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDC', '\x3', 
		'\x2', '\x2', '\x2', '\xDB', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xDC', 
		'\xDD', '\a', '$', '\x2', '\x2', '\xDD', '\x38', '\x3', '\x2', '\x2', 
		'\x2', '\xDE', '\xE2', '\a', '%', '\x2', '\x2', '\xDF', '\xE1', '\n', 
		'\x4', '\x2', '\x2', '\xE0', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xE1', 
		'\xE4', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE0', '\x3', '\x2', '\x2', 
		'\x2', '\xE2', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE3', ':', '\x3', 
		'\x2', '\x2', '\x2', '\xE4', '\xE2', '\x3', '\x2', '\x2', '\x2', '\xE5', 
		'\xE8', '\x5', '\t', '\x5', '\x2', '\xE6', '\xE8', '\x5', '\v', '\x6', 
		'\x2', '\xE7', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE6', '\x3', 
		'\x2', '\x2', '\x2', '\xE8', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xE9', 
		'\xE7', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '\xEA', '<', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xED', '\a', 
		'\xF', '\x2', '\x2', '\xEC', '\xEB', '\x3', '\x2', '\x2', '\x2', '\xED', 
		'\xF0', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xEC', '\x3', '\x2', '\x2', 
		'\x2', '\xEE', '\xEF', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xF1', '\x3', 
		'\x2', '\x2', '\x2', '\xF0', '\xEE', '\x3', '\x2', '\x2', '\x2', '\xF1', 
		'\xF5', '\a', '\f', '\x2', '\x2', '\xF2', '\xF4', '\a', '\v', '\x2', '\x2', 
		'\xF3', '\xF2', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF7', '\x3', '\x2', 
		'\x2', '\x2', '\xF5', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF6', 
		'\x3', '\x2', '\x2', '\x2', '\xF6', '\xFD', '\x3', '\x2', '\x2', '\x2', 
		'\xF7', '\xF5', '\x3', '\x2', '\x2', '\x2', '\xF8', '\xF9', '\a', '\xF', 
		'\x2', '\x2', '\xF9', '\xFA', '\a', '\f', '\x2', '\x2', '\xFA', '\xFB', 
		'\a', '\xF', '\x2', '\x2', '\xFB', '\xFD', '\a', '\f', '\x2', '\x2', '\xFC', 
		'\xEE', '\x3', '\x2', '\x2', '\x2', '\xFC', '\xF8', '\x3', '\x2', '\x2', 
		'\x2', '\xFD', '>', '\x3', '\x2', '\x2', '\x2', '\x15', '\x2', 'Q', ']', 
		'\x98', '\x9D', '\xA8', '\xAB', '\xB0', '\xC4', '\xC7', '\xCC', '\xD3', 
		'\xD9', '\xE2', '\xE7', '\xE9', '\xEE', '\xF5', '\xFC', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
