//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Final.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFinalListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class FinalBaseListener : IFinalListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] FinalParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] FinalParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] FinalParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] FinalParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign([NotNull] FinalParser.AssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign([NotNull] FinalParser.AssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.literals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiterals([NotNull] FinalParser.LiteralsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.literals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiterals([NotNull] FinalParser.LiteralsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.arithmetic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmetic([NotNull] FinalParser.ArithmeticContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.arithmetic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmetic([NotNull] FinalParser.ArithmeticContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatements([NotNull] FinalParser.StatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatements([NotNull] FinalParser.StatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.ifState"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfState([NotNull] FinalParser.IfStateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.ifState"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfState([NotNull] FinalParser.IfStateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] FinalParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] FinalParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.elif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElif([NotNull] FinalParser.ElifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.elif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElif([NotNull] FinalParser.ElifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] FinalParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] FinalParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.conState"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConState([NotNull] FinalParser.ConStateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.conState"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConState([NotNull] FinalParser.ConStateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.oneLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneLine([NotNull] FinalParser.OneLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.oneLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneLine([NotNull] FinalParser.OneLineContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
