//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Final.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FinalParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IFinalListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] FinalParser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] FinalParser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FinalParser.arithmetic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmetic([NotNull] FinalParser.ArithmeticContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FinalParser.arithmetic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmetic([NotNull] FinalParser.ArithmeticContext context);
}
